spring.application.name=NovaraLms

spring.datasource.url=jdbc:postgresql://localhost:5432/Novara_LMS
spring.datasource.username=JO
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.mongodb.database=Novara_LMS
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.docker.compose.enabled=false
spring.session.store-type=none

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=9090
server.address=0.0.0.0